"""v1_0_baseline_schema

Revision ID: 94edc0f39eba
Revises: 
Create Date: 2026-06-06 15:30:06.665281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94edc0f39eba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_entries_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_entries_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_entries_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_entries_timestamp'), ['timestamp'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='projectstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('category_level_names', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_user_id'), ['user_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('analysis_domains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=20), server_default='human', nullable=False),
    sa.Column('origin_context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_domains_project_id'), ['project_id'], unique=False)

    op.create_table('canvases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canvases', schema=None) as batch_op:
        batch_op.create_index('ix_canvases_project', ['project_id'], unique=False)

    op.create_table('code_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['code_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('code_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_categories_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_categories_project_id'), ['project_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject_id', sa.String(length=100), nullable=True),
    sa.Column('conversation_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('imported', 'in_progress', 'completed', name='conversationstatus'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('media_filename', sa.String(length=500), nullable=True),
    sa.Column('media_format', sa.String(length=10), nullable=True),
    sa.Column('media_type', sa.String(length=10), nullable=True),
    sa.Column('media_duration_seconds', sa.Float(), nullable=True),
    sa.Column('media_offset_seconds', sa.Float(), nullable=False),
    sa.Column('media_is_vbr', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_project_id'), ['project_id'], unique=False)

    op.create_table('datasets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('rater_group', sa.String(length=100), nullable=True),
    sa.Column('import_config', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_project_id'), ['project_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_filename', sa.String(length=500), nullable=False),
    sa.Column('source_format', sa.String(length=10), nullable=False),
    sa.Column('segmentation_mode', sa.Enum('paragraph', 'sentence', 'heading', 'page', 'double_newline', name='segmentationmode'), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_project_id'), ['project_id'], unique=False)

    op.create_table('equivalence_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=20), server_default='human', nullable=False),
    sa.Column('origin_context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equivalence_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equivalence_groups_project_id'), ['project_id'], unique=False)

    op.create_table('material_collections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_collections', schema=None) as batch_op:
        batch_op.create_index('ix_material_collections_project', ['project_id'], unique=False)

    op.create_table('memos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('numeric_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.create_index('ix_memos_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memos_project_id'), ['project_id'], unique=False)

    op.create_table('participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('demographics', sa.Text(), nullable=True),
    sa.Column('role_auto_filled_from', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_participants_project_identifier', ['project_id', 'identifier'], unique=True)
        batch_op.create_index('ix_participants_project_role', ['project_id', 'role'], unique=False)

    op.create_table('quote_board_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('custom_orders', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('scratchpad_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('numeric_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_hint', sa.String(length=255), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_into_type', sa.String(length=20), nullable=True),
    sa.Column('resolved_into_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scratchpad_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scratchpad_entries_project_id'), ['project_id'], unique=False)

    op.create_table('statistical_tests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.Text(), server_default='{}', nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('result_data', sa.Text(), nullable=True),
    sa.Column('valid_n', sa.Integer(), nullable=True),
    sa.Column('stale', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('origin', sa.String(length=20), server_default='human', nullable=False),
    sa.Column('origin_context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("target_type IN ('analysis_domain', 'metric_definition')", name='ck_statistical_test_target_type'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('statistical_tests', schema=None) as batch_op:
        batch_op.create_index('ix_statistical_tests_project', ['project_id'], unique=False)
        batch_op.create_index('ix_statistical_tests_target', ['target_type', 'target_id'], unique=False)

    op.create_table('text_coding_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('view_mode', sa.String(length=20), nullable=False),
    sa.Column('focal_column_ids', sa.Text(), nullable=True),
    sa.Column('dataset_filter_ids', sa.Text(), nullable=True),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('context_visibility', sa.Text(), nullable=True),
    sa.Column('hide_empty', sa.Integer(), nullable=False),
    sa.Column('starred_value_ids', sa.Text(), nullable=True),
    sa.Column('treat_as_empty', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('analysis_domain_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('member_type', sa.String(length=20), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=20), server_default='human', nullable=False),
    sa.Column('origin_context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['analysis_domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'member_type', 'member_id', name='uq_domain_member')
    )
    with op.batch_alter_table('analysis_domain_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_domain_members_domain_id'), ['domain_id'], unique=False)

    op.create_table('canvas_pending_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canvas_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canvas_pending_items', schema=None) as batch_op:
        batch_op.create_index('ix_canvas_pending_items_canvas', ['canvas_id'], unique=False)

    op.create_table('canvas_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canvas_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('snapshot_data', sa.Text(), nullable=False),
    sa.Column('theme_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canvas_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_canvas_snapshots_canvas', ['canvas_id'], unique=False)

    op.create_table('canvas_themes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canvas_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('section_type', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('doc_order', sa.Integer(), nullable=False),
    sa.Column('table_column_order', sa.Integer(), nullable=False),
    sa.Column('viz_x', sa.Float(), nullable=True),
    sa.Column('viz_y', sa.Float(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('searchable_text', sa.Text(), nullable=True),
    sa.Column('referenced_source_ids', sa.Text(), nullable=True),
    sa.Column('parent_theme_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_theme_id'], ['canvas_themes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canvas_themes', schema=None) as batch_op:
        batch_op.create_index('ix_canvas_themes_canvas', ['canvas_id'], unique=False)
        batch_op.create_index('ix_canvas_themes_canvas_doc', ['canvas_id', 'doc_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_canvas_themes_parent_theme_id'), ['parent_theme_id'], unique=False)

    op.create_table('codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('numeric_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_universal', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['code_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_codes_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_codes_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_codes_project_numeric', ['project_id', 'numeric_id'], unique=True)

    op.create_table('dataset_columns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('column_code', sa.String(length=50), nullable=True),
    sa.Column('group_code', sa.String(length=50), nullable=True),
    sa.Column('group_label', sa.String(length=255), nullable=True),
    sa.Column('column_name', sa.String(length=255), nullable=True),
    sa.Column('column_text', sa.Text(), nullable=False),
    sa.Column('column_type', sa.Enum('ordinal', 'nominal', 'binary', 'multi_select', 'numeric', 'percentage', 'open_text', 'demographic', 'skip', name='columntype'), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('scale_labels', sa.Text(), nullable=True),
    sa.Column('scale_values', sa.Text(), nullable=True),
    sa.Column('scale_points', sa.Integer(), nullable=True),
    sa.Column('numeric_min', sa.Float(), nullable=True),
    sa.Column('numeric_max', sa.Float(), nullable=True),
    sa.Column('numeric_format', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=20), server_default='imported', nullable=False),
    sa.Column('expression', sa.Text(), nullable=True),
    sa.Column('depends_on_column_ids', sa.Text(), nullable=True),
    sa.Column('stale', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('demographic_subtype', sa.String(length=40), nullable=True),
    sa.Column('equivalence_group_id', sa.Integer(), nullable=True),
    sa.Column('show_in_participant_profile', sa.Boolean(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equivalence_group_id'], ['equivalence_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dataset_columns', schema=None) as batch_op:
        batch_op.create_index('ix_dataset_columns_dataset_display_order', ['dataset_id', 'display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_columns_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index('ix_dataset_columns_dataset_sequence', ['dataset_id', 'sequence_order'], unique=False)
        batch_op.create_index('ix_dataset_columns_dataset_sequence_unique', ['dataset_id', 'sequence_order'], unique=True)
        batch_op.create_index(batch_op.f('ix_dataset_columns_equivalence_group_id'), ['equivalence_group_id'], unique=False)
        batch_op.create_index('ix_equivalence_unique_column_per_dataset', ['equivalence_group_id', 'dataset_id'], unique=True, sqlite_where=sa.text('equivalence_group_id IS NOT NULL'), postgresql_where=sa.text('equivalence_group_id IS NOT NULL'))

    op.create_table('dataset_rows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('row_identifier', sa.String(length=255), nullable=True),
    sa.Column('import_batch', sa.String(length=255), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dataset_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_rows_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_rows_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index('uq_dataset_rows_dataset_participant', ['dataset_id', 'participant_id'], unique=True, sqlite_where=sa.text('participant_id IS NOT NULL'), postgresql_where=sa.text('participant_id IS NOT NULL'))

    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('auto_name', sa.String(length=500), nullable=False),
    sa.Column('custom_name', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('source_tab', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['material_collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index('ix_materials_collection', ['collection_id'], unique=False)

    op.create_table('segment_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('segment_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_segment_groups_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('speakers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('original_label', sa.String(length=255), nullable=True),
    sa.Column('is_facilitator', sa.Integer(), nullable=False),
    sa.Column('color_index', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('speakers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_speakers_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index('ix_speakers_project_facilitator', ['project_id', 'is_facilitator'], unique=False)
        batch_op.create_index(batch_op.f('ix_speakers_project_id'), ['project_id'], unique=False)

    op.create_table('canvas_theme_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canvas_id', sa.Integer(), nullable=False),
    sa.Column('source_theme_id', sa.Integer(), nullable=False),
    sa.Column('target_theme_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('is_bidirectional', sa.Boolean(), nullable=False),
    sa.Column('line_style', sa.String(length=20), nullable=True),
    sa.Column('line_color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('source_theme_id != target_theme_id', name='ck_canvas_theme_rel_not_self'),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_theme_id'], ['canvas_themes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_theme_id'], ['canvas_themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canvas_id', 'source_theme_id', 'target_theme_id', name='uq_canvas_theme_rel_pair')
    )
    with op.batch_alter_table('canvas_theme_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canvas_theme_relationships_source_theme_id'), ['source_theme_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canvas_theme_relationships_target_theme_id'), ['target_theme_id'], unique=False)
        batch_op.create_index('ix_canvas_theme_rels_canvas', ['canvas_id'], unique=False)

    op.create_table('code_category_memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['code_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['code_id'], ['codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('code_category_memberships', schema=None) as batch_op:
        batch_op.create_index('ix_code_category_membership_unique', ['code_id', 'category_id'], unique=True)

    op.create_table('dataset_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('column_id', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_numeric', sa.Float(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['dataset_columns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['row_id'], ['dataset_rows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dataset_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_values_column_id'), ['column_id'], unique=False)
        batch_op.create_index('ix_dataset_values_row_column', ['row_id', 'column_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_dataset_values_row_id'), ['row_id'], unique=False)

    op.create_table('metric_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('input_source_type', sa.String(length=50), nullable=False),
    sa.Column('input_source_id', sa.Integer(), nullable=False),
    sa.Column('grouping_column_id', sa.Integer(), nullable=True),
    sa.Column('grouping_column_id_2', sa.Integer(), nullable=True),
    sa.Column('grouping_mode', sa.String(length=20), nullable=True),
    sa.Column('exclude_values', sa.Text(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=20), server_default='human', nullable=False),
    sa.Column('origin_context', sa.Text(), nullable=True),
    sa.Column('stale', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("input_source_type IN ('dataset_column', 'dataset_domain')", name='ck_metric_definition_source_type'),
    sa.ForeignKeyConstraint(['grouping_column_id'], ['dataset_columns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grouping_column_id_2'], ['dataset_columns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric_definitions', schema=None) as batch_op:
        batch_op.create_index('ix_metric_definitions_grouping_column', ['grouping_column_id'], unique=False)
        batch_op.create_index('ix_metric_definitions_project', ['project_id'], unique=False)
        batch_op.create_index('ix_metric_definitions_project_source', ['project_id', 'input_source_type', 'input_source_id'], unique=False)

    op.create_table('recode_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('column_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('recode_type', sa.Enum('scale_map', 'category_group', 'reverse', name='recodetype'), nullable=False),
    sa.Column('output_type', sa.Enum('numeric', 'categorical', name='outputtype'), nullable=False),
    sa.Column('mapping', sa.Text(), nullable=False),
    sa.Column('exclude_values', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_auto_detected', sa.Boolean(), nullable=False),
    sa.Column('source_definition_id', sa.Integer(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['column_id'], ['dataset_columns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_definition_id'], ['recode_definitions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recode_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recode_definitions_column_id'), ['column_id'], unique=False)

    op.create_table('segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('original_speaker_label', sa.String(length=255), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('heading_level', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_starred', sa.Integer(), nullable=False),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('is_merge_result', sa.Integer(), nullable=False),
    sa.Column('split_into_id', sa.Integer(), nullable=True),
    sa.Column('is_split_result', sa.Integer(), nullable=False),
    sa.CheckConstraint('(conversation_id IS NOT NULL AND document_id IS NULL) OR (conversation_id IS NULL AND document_id IS NOT NULL)', name='ck_segment_exactly_one_parent'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['segment_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merged_into_id'], ['segments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['split_into_id'], ['segments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_segments_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index('ix_segments_conversation_sequence', ['conversation_id', 'sequence_order'], unique=False)
        batch_op.create_index('ix_segments_conversation_starred', ['conversation_id', 'is_starred'], unique=False)
        batch_op.create_index(batch_op.f('ix_segments_document_id'), ['document_id'], unique=False)
        batch_op.create_index('ix_segments_document_sequence', ['document_id', 'sequence_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_segments_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_segments_merged_into_id'), ['merged_into_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_segments_speaker_id'), ['speaker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_segments_split_into_id'), ['split_into_id'], unique=False)

    op.create_table('code_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('dataset_value_id', sa.Integer(), nullable=True),
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('attribution', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(segment_id IS NOT NULL AND dataset_value_id IS NULL) OR (segment_id IS NULL AND dataset_value_id IS NOT NULL)', name='ck_code_application_exactly_one_target'),
    sa.ForeignKeyConstraint(['code_id'], ['codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_value_id'], ['dataset_values.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('code_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_applications_code_id'), ['code_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_applications_dataset_value_id'), ['dataset_value_id'], unique=False)
        batch_op.create_index('ix_code_applications_seg_code_unique', ['segment_id', 'code_id'], unique=True, sqlite_where=sa.text('segment_id IS NOT NULL'))
        batch_op.create_index(batch_op.f('ix_code_applications_segment_id'), ['segment_id'], unique=False)
        batch_op.create_index('ix_code_applications_value_code_unique', ['dataset_value_id', 'code_id'], unique=True, sqlite_where=sa.text('dataset_value_id IS NOT NULL'))

    op.create_table('computed_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric_definition_id', sa.Integer(), nullable=False),
    sa.Column('group_value', sa.String(length=255), nullable=True),
    sa.Column('result_data', sa.Text(), nullable=False),
    sa.Column('valid_n', sa.Integer(), nullable=False),
    sa.Column('total_n', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['metric_definition_id'], ['metric_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_definition_id', 'group_value', name='uq_computed_results_def_group')
    )
    with op.batch_alter_table('computed_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_computed_results_metric_definition_id'), ['metric_definition_id'], unique=False)
        batch_op.create_index('uq_computed_results_ungrouped', ['metric_definition_id'], unique=True, sqlite_where=sa.text('group_value IS NULL'), postgresql_where=sa.text('group_value IS NULL'))

    op.create_table('excerpt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('dataset_value_id', sa.Integer(), nullable=True),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(segment_id IS NOT NULL AND dataset_value_id IS NULL) OR (segment_id IS NULL AND dataset_value_id IS NOT NULL)', name='ck_excerpt_exactly_one_target'),
    sa.CheckConstraint('(start_offset IS NULL AND end_offset IS NULL) OR (start_offset IS NOT NULL AND end_offset IS NOT NULL)', name='ck_excerpt_offsets_both_or_neither'),
    sa.CheckConstraint('start_offset IS NULL OR (start_offset >= 0 AND end_offset > start_offset)', name='ck_excerpt_offsets_valid_range'),
    sa.ForeignKeyConstraint(['dataset_value_id'], ['dataset_values.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('excerpt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_excerpt_dataset_value_id'), ['dataset_value_id'], unique=False)
        batch_op.create_index('ix_excerpt_project_dataset_value', ['project_id', 'dataset_value_id'], unique=False)
        batch_op.create_index('ix_excerpt_project_segment', ['project_id', 'segment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_excerpt_segment_id'), ['segment_id'], unique=False)
        batch_op.create_index('ix_excerpt_segment_range', ['segment_id', 'start_offset', 'end_offset'], unique=True, sqlite_where=sa.text('segment_id IS NOT NULL AND start_offset IS NOT NULL'))
        batch_op.create_index('ix_excerpt_segment_whole', ['segment_id'], unique=True, sqlite_where=sa.text('segment_id IS NOT NULL AND start_offset IS NULL'))

    op.create_table('row_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric_definition_id', sa.Integer(), nullable=False),
    sa.Column('dataset_row_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_row_id'], ['dataset_rows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_definition_id'], ['metric_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_definition_id', 'dataset_row_id', name='uq_row_scores_metric_row')
    )
    with op.batch_alter_table('row_scores', schema=None) as batch_op:
        batch_op.create_index('ix_row_scores_metric', ['metric_definition_id'], unique=False)
        batch_op.create_index('ix_row_scores_row', ['dataset_row_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('dataset_value_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('excerpt_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('conversation_id IS NOT NULL OR dataset_value_id IS NOT NULL OR document_id IS NOT NULL', name='ck_note_at_least_one_parent'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_value_id'], ['dataset_values.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['excerpt_id'], ['excerpt.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index('ix_notes_conversation_seq', ['conversation_id', 'sequence_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_dataset_value_id'), ['dataset_value_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_document_id'), ['document_id'], unique=False)
        batch_op.create_index('ix_notes_excerpt_unique', ['excerpt_id'], unique=True, sqlite_where=sa.text('excerpt_id IS NOT NULL'))
        batch_op.create_index(batch_op.f('ix_notes_segment_id'), ['segment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_segment_id'))
        batch_op.drop_index('ix_notes_excerpt_unique', sqlite_where=sa.text('excerpt_id IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_notes_document_id'))
        batch_op.drop_index(batch_op.f('ix_notes_dataset_value_id'))
        batch_op.drop_index('ix_notes_conversation_seq')
        batch_op.drop_index(batch_op.f('ix_notes_conversation_id'))

    op.drop_table('notes')
    with op.batch_alter_table('row_scores', schema=None) as batch_op:
        batch_op.drop_index('ix_row_scores_row')
        batch_op.drop_index('ix_row_scores_metric')

    op.drop_table('row_scores')
    with op.batch_alter_table('excerpt', schema=None) as batch_op:
        batch_op.drop_index('ix_excerpt_segment_whole', sqlite_where=sa.text('segment_id IS NOT NULL AND start_offset IS NULL'))
        batch_op.drop_index('ix_excerpt_segment_range', sqlite_where=sa.text('segment_id IS NOT NULL AND start_offset IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_excerpt_segment_id'))
        batch_op.drop_index('ix_excerpt_project_segment')
        batch_op.drop_index('ix_excerpt_project_dataset_value')
        batch_op.drop_index(batch_op.f('ix_excerpt_dataset_value_id'))

    op.drop_table('excerpt')
    with op.batch_alter_table('computed_results', schema=None) as batch_op:
        batch_op.drop_index('uq_computed_results_ungrouped', sqlite_where=sa.text('group_value IS NULL'), postgresql_where=sa.text('group_value IS NULL'))
        batch_op.drop_index(batch_op.f('ix_computed_results_metric_definition_id'))

    op.drop_table('computed_results')
    with op.batch_alter_table('code_applications', schema=None) as batch_op:
        batch_op.drop_index('ix_code_applications_value_code_unique', sqlite_where=sa.text('dataset_value_id IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_code_applications_segment_id'))
        batch_op.drop_index('ix_code_applications_seg_code_unique', sqlite_where=sa.text('segment_id IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_code_applications_dataset_value_id'))
        batch_op.drop_index(batch_op.f('ix_code_applications_code_id'))

    op.drop_table('code_applications')
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_segments_split_into_id'))
        batch_op.drop_index(batch_op.f('ix_segments_speaker_id'))
        batch_op.drop_index(batch_op.f('ix_segments_merged_into_id'))
        batch_op.drop_index(batch_op.f('ix_segments_group_id'))
        batch_op.drop_index('ix_segments_document_sequence')
        batch_op.drop_index(batch_op.f('ix_segments_document_id'))
        batch_op.drop_index('ix_segments_conversation_starred')
        batch_op.drop_index('ix_segments_conversation_sequence')
        batch_op.drop_index(batch_op.f('ix_segments_conversation_id'))

    op.drop_table('segments')
    with op.batch_alter_table('recode_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recode_definitions_column_id'))

    op.drop_table('recode_definitions')
    with op.batch_alter_table('metric_definitions', schema=None) as batch_op:
        batch_op.drop_index('ix_metric_definitions_project_source')
        batch_op.drop_index('ix_metric_definitions_project')
        batch_op.drop_index('ix_metric_definitions_grouping_column')

    op.drop_table('metric_definitions')
    with op.batch_alter_table('dataset_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_values_row_id'))
        batch_op.drop_index('ix_dataset_values_row_column')
        batch_op.drop_index(batch_op.f('ix_dataset_values_column_id'))

    op.drop_table('dataset_values')
    with op.batch_alter_table('code_category_memberships', schema=None) as batch_op:
        batch_op.drop_index('ix_code_category_membership_unique')

    op.drop_table('code_category_memberships')
    with op.batch_alter_table('canvas_theme_relationships', schema=None) as batch_op:
        batch_op.drop_index('ix_canvas_theme_rels_canvas')
        batch_op.drop_index(batch_op.f('ix_canvas_theme_relationships_target_theme_id'))
        batch_op.drop_index(batch_op.f('ix_canvas_theme_relationships_source_theme_id'))

    op.drop_table('canvas_theme_relationships')
    with op.batch_alter_table('speakers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_speakers_project_id'))
        batch_op.drop_index('ix_speakers_project_facilitator')
        batch_op.drop_index(batch_op.f('ix_speakers_participant_id'))

    op.drop_table('speakers')
    with op.batch_alter_table('segment_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_segment_groups_conversation_id'))

    op.drop_table('segment_groups')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index('ix_materials_collection')

    op.drop_table('materials')
    with op.batch_alter_table('dataset_rows', schema=None) as batch_op:
        batch_op.drop_index('uq_dataset_rows_dataset_participant', sqlite_where=sa.text('participant_id IS NOT NULL'), postgresql_where=sa.text('participant_id IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_dataset_rows_participant_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_rows_dataset_id'))

    op.drop_table('dataset_rows')
    with op.batch_alter_table('dataset_columns', schema=None) as batch_op:
        batch_op.drop_index('ix_equivalence_unique_column_per_dataset', sqlite_where=sa.text('equivalence_group_id IS NOT NULL'), postgresql_where=sa.text('equivalence_group_id IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_dataset_columns_equivalence_group_id'))
        batch_op.drop_index('ix_dataset_columns_dataset_sequence_unique')
        batch_op.drop_index('ix_dataset_columns_dataset_sequence')
        batch_op.drop_index(batch_op.f('ix_dataset_columns_dataset_id'))
        batch_op.drop_index('ix_dataset_columns_dataset_display_order')

    op.drop_table('dataset_columns')
    with op.batch_alter_table('codes', schema=None) as batch_op:
        batch_op.drop_index('ix_codes_project_numeric')
        batch_op.drop_index(batch_op.f('ix_codes_project_id'))
        batch_op.drop_index(batch_op.f('ix_codes_category_id'))

    op.drop_table('codes')
    with op.batch_alter_table('canvas_themes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canvas_themes_parent_theme_id'))
        batch_op.drop_index('ix_canvas_themes_canvas_doc')
        batch_op.drop_index('ix_canvas_themes_canvas')

    op.drop_table('canvas_themes')
    with op.batch_alter_table('canvas_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_canvas_snapshots_canvas')

    op.drop_table('canvas_snapshots')
    with op.batch_alter_table('canvas_pending_items', schema=None) as batch_op:
        batch_op.drop_index('ix_canvas_pending_items_canvas')

    op.drop_table('canvas_pending_items')
    with op.batch_alter_table('analysis_domain_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_domain_members_domain_id'))

    op.drop_table('analysis_domain_members')
    op.drop_table('text_coding_configs')
    with op.batch_alter_table('statistical_tests', schema=None) as batch_op:
        batch_op.drop_index('ix_statistical_tests_target')
        batch_op.drop_index('ix_statistical_tests_project')

    op.drop_table('statistical_tests')
    with op.batch_alter_table('scratchpad_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scratchpad_entries_project_id'))

    op.drop_table('scratchpad_entries')
    op.drop_table('quote_board_configs')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index('ix_participants_project_role')
        batch_op.drop_index('ix_participants_project_identifier')
        batch_op.drop_index(batch_op.f('ix_participants_project_id'))

    op.drop_table('participants')
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memos_project_id'))
        batch_op.drop_index('ix_memos_entity')

    op.drop_table('memos')
    with op.batch_alter_table('material_collections', schema=None) as batch_op:
        batch_op.drop_index('ix_material_collections_project')

    op.drop_table('material_collections')
    with op.batch_alter_table('equivalence_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equivalence_groups_project_id'))

    op.drop_table('equivalence_groups')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_project_id'))

    op.drop_table('documents')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_project_id'))

    op.drop_table('datasets')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_project_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('code_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_categories_project_id'))
        batch_op.drop_index(batch_op.f('ix_code_categories_parent_id'))

    op.drop_table('code_categories')
    with op.batch_alter_table('canvases', schema=None) as batch_op:
        batch_op.drop_index('ix_canvases_project')

    op.drop_table('canvases')
    with op.batch_alter_table('analysis_domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_domains_project_id'))

    op.drop_table('analysis_domains')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_user_id'))

    op.drop_table('projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('audit_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_entries_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_entries_project_id'))
        batch_op.drop_index(batch_op.f('ix_audit_entries_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_entries_action'))

    op.drop_table('audit_entries')
    # ### end Alembic commands ###
